ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

define PINFO
PINFO DESCRIPTION=GPIO driver
endef

NAME = gpio-siul2
INSTALLDIR = sbin
# include $(MKFILES_ROOT)/qmacros.mk

USEFILE=$(PROJECT_ROOT)/gpio-siul2.use
# EXTRA_SRCVPATH = $(EXTRA_SRCVPATH_$(SECTION))

# PRE_SRCVPATH = $(foreach var,$(filter a, $(VARIANTS)),$(CPU_ROOT)/$(subst $(space),.,$(patsubst a,dll,$(filter-out g, $(VARIANTS)))))


#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

