#!groovy

//region Declarative Pipeline

pipeline {
 options {
    timestamps() // Prepend all console outputs with a timestamp
  }

    agent {
        docker {
            image 'test:2.0'
            args '-v ${WORKSPACE}/bsp_working_dir:/home/jenkins/bsp_working_dir'
        }
    }

    stages {

      stage('Install QNX license') {
      steps {
        script {
          sh 'mkdir -p $HOME/.qnx/license'

          withCredentials([file(
            credentialsId: 'QNX_LICENSES_PROAI_CV',
            variable: 'LICENSE_FILE')])
          {
            sh """#!/bin/bash
              cp --verbose "${LICENSE_FILE}" "\$HOME/.qnx/license/licenses"
            """
          }
        }
      }
    }
      
      stage('Download BSP source code'){
      steps {
        git branch : 'master',
          credentialsId: 'Github', url: 'https://github.com/Yihan1993/qnx_devops.git'
          sh 'pwd'
          echo 'git checkout bsp code'
      }
      }

        stage ('Build QNX BSP Image') {
            steps{
                sh """#!/bin/bash
            # Ensure QNX environment variables are available
            source /opt/qnx700/qnxsdp-env.sh

            cd /home/jenkins/bsp_working_dir 
            pwd
            make clean && make all
            """

            }
        }
    }
          
}
