# This is an automatically generated record.
# The area between QNX Internal Start and QNX Internal End is controlled by
# the QNX IDE properties.

ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

#===== NAME - name of the project (default - name of project directory).
NAME=test_gpio

define PINFO
PINFO DESCRIPTION = "Test app for working with the S32 SIUL2 GPIO resource manager"
endef

# Including files here to make the LIBPREF_x and LIBPOST_x macros below work

include $(MKFILES_ROOT)/qmacros.mk

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk


#===== CCFLAGS - add the flags to the C compiler command line.
CCFLAGS+=-Werror -Wall

OPTIMIZE_TYPE_g=none
OPTIMIZE_TYPE=$(OPTIMIZE_TYPE_$(filter g, $(VARIANTS)))
